### ISSUE TITLE
[Enhancement] Open links on new tab, and multi-key, (and possibly background browser music?)

### ISSUE THREAD

**Issue by 100sidedice** [prakhartiwari0/my-web-shortcuts#73]
Keyboard shortcuts for new tab, and perhaps also multi-key shortcuts (You may be able to do it by storing them in an array or similar, so I could type 1-2-3 and it would activate)

Also, you managed to get sound with the extension... this is the first one that I've seen that can do that.
So, if you can find a way to do let users upload their own background audio/music that could be sick.

**Comment by 3xp11i** [comment]
Heyy there!
A new issue opened in a very long time, glad to see people are using it and want it to improve haha (which I'm working on rn)!

Here are some questions:
> Keyboard shortcuts for new tab,
- Keyboard shortcuts to open a new Tab? Why? Is `CTRL + T` not good enough or something? Or do you want a custom keyboard shortcut to open a new tab? 
		Whatever it may be, this extension is solely focused on creating shortcuts for websites at least for now, I haven't and don't have any plans to have it interfere with the browser shortcuts too simply because they are just annoying to work with. However, if you can describe more I can think of another solution, maybe add this feature in another extension I build or I could suggest you a different extension that already does this nicely.

>  and perhaps also multi-key shortcuts (You may be able to do it by storing them in an array or similar, so I could type 1-2-3 and it would activate)
- Multi-Key shortcuts, hmm that is interesting and I think it's already on my list but hasn't been on the top priority. I may add it eventually but you would have to wait for it, currently, a whole new version with loads of new updates is coming up so stay tuned for that ;)

> Also, you managed to get sound with the extension... this is the first one that I've seen that can do that.
So, if you can find a way to let users upload their own background audio/music that could be sick.
- Haha yeah I wanted to make using it feel like a proper tool and added sounds for fun. Letting users upload their own bg audio/music seems like too much and not really a worth-it feature according to me. I could have different sets of sounds and all but the problem is, not many people would use it as it's just a fun thing and not related to the functionality, and it would also increase the size of the extension unnecessarily. Even if I let users upload their little sounds that would require loads of other things too. But you know what, I may add just one option to let user upload a custom click sound somewhere inside for people like you to play with, but please don't expect it to be soon, sorry 😓
